ex1:
	mkdir -p  build
	gcc -Wall -Werror -o ./build/ex1 exercise1/main.c
	./build/ex1

ex2:
	mkdir -p  build
	gcc -Wall -Werror -o ./build/ex2 exercise2/main.c
	./build/ex2

ex3:
	mkdir -p  build
	gcc -Wall -Werror -o ./build/ex3 exercise3/main.c
	./build/ex3

zip:
	zip lab1_ex1.zip main.c


