SHELL = /bin/sh
.SUFFIXES:
.SUFFIXES: .c .o
LDCONFIG = ldconfig
FLAGS = -std=c11 -Werror -lm $(shell pkg-config --cflags --libs check)



sensor_node:
	mkdir -p build
	gcc -Wall sensor_node.c -o ./build/sensor_node -ltcpsock -ldplist  $(FLAGS)
	./build/sensor_node

s1:
	

test_server:
	mkdir -p build
	gcc -Wall test_server.c -o ./build/test_server -ltcpsock -ldplist  $(FLAGS)
	./build/test_server


test_debug:
	@echo -e '\n*******************************'
	@echo -e '*** Compiling for UNIT TEST ***'
	@echo -e '*******************************'
	mkdir -p build
	gcc -g -Wall main.c sensor_db.c -o ./build/exercise2 -lsqlite3 $(FLAGS)
	@echo -e '\n*************************'
	@echo -e '*** Running UNIT TEST ***'
	@echo -e '*************************'
	export CK_FORK=no ; gdb -q -tui ./build/exercise2

libtcpsock.so: lib/tcpsock.o
	cc -shared -o libtcpsock.so lib/tcpsock.o
	sudo cp libtcpsock.so /usr/lib
	sudo $(LDCONFIG)
	rm lib/tcpsock.o


shared_tcpsock.o:
	gcc lib/tcpsock.c -o lib/tcpsock.o -fPIC -c


zip:
	zip lab7_ex2.zip connmgr.c connmgr.h config.h lib/dplist.c lib/dplist.h lib/tcpsock.c lib/tcpsock.h
